# Generated by Django 4.2.5 on 2023-09-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_friends_friendshpirequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshpirequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('sent', 'Sent'), ('rejected', 'Rejected')], default='sent', max_length=20),
        ),
    ]
